# docker-compose.yml
version: '3.8'

services:
  influxdb:
    image: influxdb:1.8.10
    container_name: k6-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6123
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - k6-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - k6-network
    depends_on:
      - influxdb
    restart: unless-stopped

  k6:
    image: grafana/k6:latest
    container_name: k6-runner
    volumes:
      - ./k6/scripts:/scripts
      - ./k6/data:/data
    networks:
      - k6-network
    depends_on:
      - influxdb
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    profiles:
      - testing

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  k6-network:
    driver: bridge
