apiVersion: 1

datasources:
  - name: InfluxDB-K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: k6
    password: k6123
    isDefault: true
    jsonData:
      timeInterval: "5s"
      httpMode: GET
    secureJsonData:
      password: k6123
