name: K6 Load Test

on: [push]

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run scenario test
        run: k6 run scripts/scenario.js
