on:
  push:
    branches:
      - main
      - master

jobs:
  k6-load-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 test
        run: k6 run --out influxdb=http://k6:k6pass@localhost:8086/k6 scripts/scenario.js
