on:
  push:
    branches:
      - main
      - master

jobs:
  k6-load-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install k6 on Windows
        run: |
          choco install k6 -y

      - name: Run k6 test
        run: k6 run --out influxdb=http://k6:k6pass@localhost:8086/k6 scripts/scenario.js
